### ISSUE TITLE
set of steps in to creating the inline web3 jawl versionהוראות ליצירת חשבון חדש | מה צריך בשביל להתחבר?

### ISSUE THREAD

**Issue by shantupai** [shantupai/sound-garbege#6]
1. creating github jawl project- check
2. sharing the git hub prject-

**Comment by eranws** [comment]
Are these the instructions for creating a new account wallet for a new ~~user~~ Energizer?

**Comment by shantupai** [comment]
[מדריך באנגלית לפתיחת ארנק ב- מטה מאסק
https://youtu.be/U0GoMFUnZrk

**Comment by eranws** [comment]
כמה השתנה בשלושה חודשים
וולאק ווב שלוש
אבל נראה לי שאנחנו בכיוון
מרכז מאמצים לכיוון #31
